services:
  db:
    build: infra/postgresql/.
    environment:
      PGUSER: ${PGUSER}
      PGDATABASE: ${PGDATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: on-failure:3
    networks:
      - app_net

  nginx:
    image: nginx:1.29
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/static
    networks:
      - app_net
    depends_on:
      core:
        condition: service_healthy

  core:
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      PGUSER: ${PGUSER}
      PGDATABASE: ${PGDATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
    volumes:
      - ./src:/usr/src/app
      - static:/usr/src/app/static
    networks:
      - app_net
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  static:
  postgres_data:
networks:
  app_net:
    driver: bridge